apiVersion: "serving.kserve.io/v1alpha1"
kind: "TrainedModel"
metadata:
  name: "speculative-llama"
spec:
  inferenceService: triton-is
  model:
    framework: transformers
    storageUri: s3://finalised-models/model-repository/speculative-llama
    memory: "5Gi"  