apiVersion: apps/v1
kind: Deployment
metadata:
  name: k6
  labels:
    app: k6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k6
  template:
    metadata:
      labels:
        app: k6
    spec:
      containers:
        - name: k6
          image: grafana/k6:0.54.0
          command: ["k6", "run", "/etc/k6-script/k6-script.js"]  # Run k6 script from the mounted file
          env:
            - name: K6_WEB_DASHBOARD
              value: "true"  # Enable the k6 web dashboard
          volumeMounts:
            - name: k6-script-volume
              mountPath: /etc/k6-script  # Mount the ConfigMap as a volume
              readOnly: true  # Make it read-only since it's only for reading the script
          ports:
            - containerPort: 5665  # Expose port 5665 for the k6 web dashboard
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      volumes:
        - name: k6-script-volume
          configMap:
            name: k6-script  # Reference the ConfigMap we created
