apiVersion: v1
kind: Service
metadata:
  name: k6-service
  labels:
    app: k6
spec:
  selector:
    app: k6
  ports:
    - protocol: TCP
      port: 5665         # External port you will access
      targetPort: 5665    # Container port