apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Values.inferenceService.name }}
  annotations:
    serving.knative.openshift.io/enablePassthrough: "true"
    sidecar.istio.io/inject: "true"
    sidecar.istio.io/rewriteAppHTTPProbers: "true"
    serving.kserve.io/deploymentMode: RawDeployment
    serving.kserve.io/logLevel: "debug"
    autoscaling.knative.dev/target: "{{ .Values.inferenceService.targetReplicas }}"
spec:
  predictor:
    minReplicas: 1
    scaleTarget: {{ .Values.inferenceService.targetReplicas }}
    serviceAccountName: {{ .Values.inferenceService.serviceAccountName }}
    model:
      modelFormat:
        name: transformers
      runtime: {{ .Values.servingRuntime.name }}
      resources:
        requests:
          cpu: {{ .Values.inferenceService.requests.cpu }}
          memory: {{ .Values.inferenceService.requests.memory }}
        limits:
          cpu: {{ .Values.inferenceService.limits.cpu }}
          memory: {{ .Values.inferenceService.limits.memory }}
